"""database_catalog

Revision ID: 3cb626dadafd
Revises: c9e1f7a4b2d0
Create Date: 2026-04-23 19:11:06.028776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb626dadafd'
down_revision: Union[str, None] = 'c9e1f7a4b2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_catalogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dialect', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_catalogs_project_id'), 'database_catalogs', ['project_id'], unique=True)
    op.create_table('catalog_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['database_catalogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'schema_name', 'name')
    )
    op.create_index(op.f('ix_catalog_entities_catalog_id'), 'catalog_entities', ['catalog_id'], unique=False)
    op.create_table('catalog_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=255), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['catalog_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_columns_entity_id'), 'catalog_columns', ['entity_id'], unique=False)
    op.create_table('catalog_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('on_delete', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['database_catalogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_entity_id'], ['catalog_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['catalog_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_relations_catalog_id'), 'catalog_relations', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_catalog_relations_from_entity_id'), 'catalog_relations', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_catalog_relations_to_entity_id'), 'catalog_relations', ['to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_relations_to_entity_id'), table_name='catalog_relations')
    op.drop_index(op.f('ix_catalog_relations_from_entity_id'), table_name='catalog_relations')
    op.drop_index(op.f('ix_catalog_relations_catalog_id'), table_name='catalog_relations')
    op.drop_table('catalog_relations')
    op.drop_index(op.f('ix_catalog_columns_entity_id'), table_name='catalog_columns')
    op.drop_table('catalog_columns')
    op.drop_index(op.f('ix_catalog_entities_catalog_id'), table_name='catalog_entities')
    op.drop_table('catalog_entities')
    op.drop_index(op.f('ix_database_catalogs_project_id'), table_name='database_catalogs')
    op.drop_table('database_catalogs')
    # ### end Alembic commands ###
