"""projects_and_profiles

Revision ID: fafa581fd3b0
Revises: faca39b0125c
Create Date: 2026-04-13 00:34:41.405722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fafa581fd3b0'
down_revision: Union[str, None] = 'faca39b0125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('project_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('main_stack', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('architecture_summary', sa.Text(), nullable=True),
    sa.Column('product_context', sa.Text(), nullable=True),
    sa.Column('business_rules', sa.Text(), nullable=True),
    sa.Column('team_context', sa.Text(), nullable=True),
    sa.Column('default_language', sa.String(length=50), nullable=True),
    sa.Column('documentation_url', sa.Text(), nullable=True),
    sa.Column('figma_url', sa.Text(), nullable=True),
    sa.Column('board_url', sa.Text(), nullable=True),
    sa.Column('api_base_url', sa.Text(), nullable=True),
    sa.Column('deployment_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_profiles_project_id'), 'project_profiles', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_profiles_project_id'), table_name='project_profiles')
    op.drop_table('project_profiles')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
